name: lead_center
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  animate_do: ^3.3.4
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.7.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  shared_preferences: ^2.2.3
  syncfusion_flutter_charts: ^26.2.7

dev_dependencies:
  change_app_package_name: ^1.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    # - google_fonts/montserrat_alternates/
